Presentation/SmartStore.Web/Administration/Controllers/ThemeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using SmartStore.Admin.Models.Themes;
using SmartStore.Collections;
using SmartStore.Core;
using SmartStore.Core.Domain.Themes;
using SmartStore.Core.Localization;
using SmartStore.Core.Packaging;
using SmartStore.Core.Themes;
using SmartStore.Services;
using SmartStore.Services.Configuration;
using SmartStore.Services.Security;
using SmartStore.Services.Stores;
using SmartStore.Services.Themes;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Mvc;
using SmartStore.Web.Framework.Themes;

namespace SmartStore.Admin.Controllers
{
	[AdminAuthorize]
    public partial class ThemeController : AdminControllerBase
	{
		#region Fields

        private readonly ISettingService _settingService;
        private readonly IThemeRegistry _themeRegistry;
        private readonly IThemeVariablesService _themeVarService;
		private readonly IStoreService _storeService;
		private readonly IPackageManager _packageManager;
		private readonly ICommonServices _services;
		private readonly IThemeContext _themeContext;
		private readonly Lazy<IThemeFileResolver> _themeFileResolver;

	    #endregion

		#region Constructors

        public ThemeController(
            ISettingService settingService, 
			IThemeRegistry themeRegistry,
            IThemeVariablesService themeVarService,
			IStoreService storeService,
			IPackageManager packageManager,
			ICommonServices services,
			IThemeContext themeContext,
			Lazy<IThemeFileResolver> themeFileResolver)
		{
            this._settingService = settingService;
            this._themeVarService = themeVarService;
            this._themeRegistry = themeRegistry;
			this._storeService = storeService;
			this._packageManager = packageManager;
			this._services = services;
			this._themeContext = themeContext;
			this._themeFileResolver = themeFileResolver;
		}

		#endregion 

        #region Methods

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List(int? storeId)
        {
            if (!_services.Permissions.Authorize(StandardPermissionProvider.ManageThemes))
                return AccessDeniedView();

			int selectedStoreId = storeId ?? _services.StoreContext.CurrentStore.Id;
			var themeSettings = _settingService.LoadSetting<ThemeSettings>(selectedStoreId);
            var model = themeSettings.ToModel();

            var commonListItems = new List<SelectListItem> 
            {
                new SelectListItem { Value = "0", Text = T("Common.Auto") },
                new SelectListItem { Value = "1", Text = T("Common.No") },
                new SelectListItem { Value = "2", Text = T("Common.Yes") }
            };

            model.AvailableBundleOptimizationValues.AddRange(commonListItems);
            model.AvailableBundleOptimizationValues.FirstOrDefault(x => int.Parse(x.Value) == model.BundleOptimizationEnabled).Selected = true;

            // add theme configs
            model.DesktopThemes.AddRange(GetThemes(false, themeSettings));
            model.MobileThemes.AddRange(GetThemes(true, themeSettings));

			model.StoreId = selectedStoreId;
			model.AvailableStores = _storeService.GetAllStores().ToSelectListItems();

            return View(model);
        }

        private IList<ThemeManifestModel> GetThemes(bool mobile, ThemeSettings themeSettings, bool includeHidden = true)
        {
			var themes = from m in _themeRegistry.GetThemeManifests(includeHidden)
                                where m.MobileTheme == mobile
                                select PrepareThemeManifestModel(m, themeSettings);

			var sortedThemes = themes.ToArray().SortTopological(StringComparer.OrdinalIgnoreCase).Cast<ThemeManifestModel>();

			return sortedThemes.OrderByDescending(x => x.IsActive).ToList();
        }

		protected virtual ThemeManifestModel PrepareThemeManifestModel(ThemeManifest manifest, ThemeSettings themeSettings)
        {
            var model = new ThemeManifestModel
                {
                    Name = manifest.ThemeName,
					BaseTheme = manifest.BaseThemeName,
                    Title = manifest.ThemeTitle,
                    Description = manifest.PreviewText,
                    Author = manifest.Author,
					Url = manifest.Url,
                    Version = manifest.Version,
                    IsMobileTheme = manifest.MobileTheme,
                    SupportsRtl = manifest.SupportRtl,
                    PreviewImageUrl = manifest.PreviewImageUrl.HasValue() ? manifest.PreviewImageUrl : "{0}/{1}/preview.png".FormatInvariant(manifest.Location, manifest.ThemeName),
                    IsActive = manifest.MobileTheme ? themeSettings.DefaultMobileTheme == manifest.ThemeName : themeSettings.DefaultDesktopTheme == manifest.ThemeName,
					State = manifest.State
                };

			if (HostingEnvironment.VirtualPathProvider.FileExists("{0}/{1}/Views/Shared/ConfigureTheme.cshtml".FormatInvariant(manifest.Location, manifest.ThemeName)))
			{
				model.IsConfigurable = true;
			}
            
            return model;
        }

		[HttpPost, ActionName("List")]
        public ActionResult ListPost(ThemeListModel model)
        {
			if (!_services.Permissions.Authorize(StandardPermissionProvider.ManageThemes))
                return AccessDeniedView();

			var themeSettings = _settingService.LoadSetting<ThemeSettings>(model.StoreId);

            bool showRestartNote = model.MobileDevicesSupported != themeSettings.MobileDevicesSupported;

            bool mobileThemeSwitched = false;
            bool themeSwitched = themeSettings.DefaultDesktopTheme.IsCaseInsensitiveEqual(model.DefaultDesktopTheme);
            if (!themeSwitched)
            {
                themeSwitched = themeSettings.DefaultMobileTheme.IsCaseInsensitiveEqual(model.DefaultMobileTheme);
                mobileThemeSwitched = themeSwitched;
            }

            if (themeSwitched)
            {
                _services.EventPublisher.Publish<ThemeSwitchedEvent>(new ThemeSwitchedEvent { 
                    IsMobile = mobileThemeSwitched,
                    OldTheme = mobileThemeSwitched ? themeSettings.DefaultMobileTheme : themeSettings.DefaultDesktopTheme,
                    NewTheme = mobileThemeSwitched ? model.DefaultMobileTheme : model.DefaultDesktopTheme
                });
            }

            themeSettings = model.ToEntity(themeSettings);
			_settingService.SaveSetting(themeSettings, model.StoreId);
            
            // activity log
			_services.CustomerActivity.InsertActivity("EditSettings", T("ActivityLog.EditSettings"));

			NotifySuccess(T("Admin.Configuration.Updated"));

            if (showRestartNote)
            {
				NotifyInfo(T("Admin.Common.RestartAppRequest"));
            }

			return RedirectToAction("List", new { storeId = model.StoreId });
        }

        public ActionResult Configure(string theme, int storeId)
        {
			if (!_services.Permissions.Authorize(StandardPermissionProvider.ManageThemes))
                return AccessDeniedView();

            if (!_themeRegistry.ThemeManifestExists(theme))
            {
				return RedirectToAction("List", new { storeId = storeId });
            }

            var model = new ConfigureThemeModel
            {
                ThemeName = theme,
				StoreId = storeId,
				AvailableStores = _storeService.GetAllStores().ToSelectListItems()
            };

			ViewData["ConfigureThemeUrl"] = Url.Action("Configure", new { theme = theme });
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormNameAttribute("save-continue", "continueEditing")]
		public ActionResult Configure(string theme, int storeId, IDictionary<string, object> values, bool continueEditing)
        {
			if (!_services.Permissions.Authorize(StandardPermissionProvider.ManageThemes))
                return AccessDeniedView();

            if (!_themeRegistry.ThemeManifestExists(theme))
            {
				return RedirectToAction("List", new { storeId = storeId });
            }		

			// get current for later restore on parse error
			var currentVars = _themeVarService.GetThemeVariables(theme, storeId);
			
            // save now
			values = FixThemeVarValues(values);
			_themeVarService.SaveThemeVariables(theme, storeId, values);

			// check for parsing error
			var manifest = _themeRegistry.GetThemeManifest(theme);
			string error = ValidateLess(manifest, storeId);
			if (error.HasValue())
			{
				// restore previous vars
				try
				{
					_themeVarService.DeleteThemeVariables(theme, storeId);
				}
				finally
				{
					// we do it here to absolutely ensure that this gets called
					_themeVarService.SaveThemeVariables(theme, storeId, currentVars);
				}

				TempData["LessParsingError"] = error.Trim().TrimStart('\r', '\n', '/', '*').TrimEnd('*', '/', '\r', '\n');
				TempData["OverriddenThemeVars"] = values;
				NotifyError(T("Admin.Configuration.Themes.Notifications.ConfigureError"));
				return RedirectToAction("Configure", new { theme = theme, storeId = storeId });
			}

            // activity log
			_services.CustomerActivity.InsertActivity("EditThemeVars", T("ActivityLog.EditThemeVars"), theme);

			NotifySuccess(T("Admin.Configuration.Themes.Notifications.ConfigureSuccess"));

			return continueEditing ?
				RedirectToAction("Configure", new { theme = theme, storeId = storeId }) :
				RedirectToAction("List", new { storeId = storeId });
        }

		private IDictionary<string, object> FixThemeVarValues(IDictionary<string, object> values)
		{
			var fixedDict = new Dictionary<string, object>();
			
			foreach (var kvp in values)
			{
				var value = kvp.Value;

				var strValue = string.Empty;

				var arrValue = value as string[];
				if (arrValue != null)
				{

Presentation/SmartStore.Web/Administration/Views/Shared/Delete.cshtml
@model SmartStore.Web.Framework.Mvc.DeleteConfirmationModel
@*codehint: sm-edit*@
@using (Html.BeginForm(Model.ActionName, Model.ControllerName, new { id = Model.Id }, FormMethod.Post, new { style = "margin:0;" })) {
    <div class="dialog-content-container">
        <p>
            @T("Admin.Common.DeleteConfirmation")
        </p>
		<div style="margin-top:18px;" class="pull-right">
            <button type="submit" class="btn btn-danger entity-commit-trigger" value='@T("Admin.Common.Delete")' data-commit-type="@Model.EntityType" data-commit-action="delete" data-commit-id="@Model.Id">
                @T("Admin.Common.Delete")
            </button>
            <button type="button" class="btn btn-link" onclick="closeModalWindow(); return false;">
                @T("Admin.Common.NoCancel")
            </button>
        </div>
    </div>
}

Presentation/SmartStore.Web/Administration/Views/Shared/Menu.cshtml
@model TreeNode<SmartStore.Web.Framework.UI.MenuItem>

@*@using Telerik.Web.Mvc.UI;*@
@using SmartStore.Services.Security;
@using SmartStore.Core.Domain.Security;
@using SmartStore.Collections;
@using SmartStore.Web.Framework.UI;

@functions {
    public string GetNodeLink(TreeNode<SmartStore.Web.Framework.UI.MenuItem> node) 
    {
        if (node.HasChildren) 
        {
            return "javascript:void(0)";
        }
        return node.Value.GenerateUrl(this.ViewContext.RequestContext);
    }

    public string GetItemText(TreeNode<SmartStore.Web.Framework.UI.MenuItem> node)
    {
        string result = null;
        
        if (node.Value.ResKey.HasValue())
        {
            result = T(node.Value.ResKey).ToHtmlString();
		}

		if (!result.HasValue() || result.IsCaseInsensitiveEqual(node.Value.ResKey))
        {
            result = node.Value.Text;
        }

        return result;
    }
}

<ul class="nav">
@{
    foreach (var node in Model.Children)
    {
        var item = node.Value;

        if (!item.Visible)
        {
            continue;
        }
        
        var imageUrl = item.ImageUrl;
        if (!imageUrl.HasValue())
        {
            imageUrl = "~/Administration/Content/images/ap-default-white.png";
        }

        string itemText = GetItemText(node);

        if (ViewBag.SelectedMenuItem == itemText)
        {
            //item.Selected = true;
        }

        var itemUrl = GetNodeLink(node);

        <li data-id="@item.Id" @Html.Attr("class", "dropdown", node.HasChildren)>
			<a href="@itemUrl" data-target="#" @Html.Attr("class", "dropdown-toggle", node.HasChildren)>
				@if (item.Icon.HasValue())
				{
					<i class="fa fa-fw fa-@item.Icon"></i>
				}
				else
				{
					<img class="sm-icon" src="@Url.Content(imageUrl)" alt="" />
				}
				<span class="navbar-label">@itemText</span>
			</a>
            @if (node.HasChildren)
            {
                @CreateDropdown(node.Children, true)
            }
        </li>
        
    }   
}

</ul>


@helper CreateDropdown(IEnumerable<TreeNode<SmartStore.Web.Framework.UI.MenuItem>> nodes, bool isRoot)
{
    var isFirst = true;
	var hasIcons = nodes.Any(x => x.Value.Icon.HasValue());
    
    <ul class='dropdown-menu'>
    @foreach (var node in nodes)
    {
        var item = node.Value;

        if (!item.Visible)
        {
            continue;
        }
        
        string itemText = GetItemText(node);

        if (item.IsGroupHeader)
        {
            if (!isFirst)
            {
                <li class="divider"></li>
            }
            if (item.Text.HasValue() && item.Text != "[SKIP]")
            {
                <li data-id="@item.Id" class="nav-header">@itemText</li>
            }
            isFirst = false;
            continue;
        }

        string liClass = null;
        if (isRoot)
        {
			liClass = ""; //"drop-list-item";
            if (node.HasChildren)
            {
                liClass += " dropdown-submenu";
            }
        }
        <li data-id="@item.Id" class='@liClass'>
            <a href="@GetNodeLink(node)">
				@if (hasIcons)
				{
					var iconClass = "fa fa-fw";
					if (node.Value.Icon.HasValue())
					{
						iconClass += " fa-" + node.Value.Icon;
					}
					<i class='@iconClass'></i>
				}
                @itemText
            </a>
            @if (node.HasChildren)
            {
                @CreateDropdown(node.Children, false)
            }
        </li>
        
        isFirst = false;
    }
    </ul>
}

<script type="text/javascript">

    $(function () {
    	$('.navbar ul.nav > li.dropdown').navbar({
    		menuAim: {
    			rowSelector: "li.dropdown-submenu",
    			submenuSelector: "*",
    		}
    	});
    });

</script>

Presentation/SmartStore.Web/Administration/Views/Shared/Navbar.cshtml
@using SmartStore.Core.Domain.Stores;
@using SmartStore.Services.Customers;
@using SmartStore.Services.Stores;

@{
    var currentCustomer = this.WorkContext.CurrentCustomer;
	var currentLanguage = this.WorkContext.WorkingLanguage;
	var userName = (string)ViewBag.UserName;
	var stores = (IList<Store>)ViewBag.Stores;
	string currentLanguageCode = currentLanguage.UniqueSeoCode.EmptyNull().ToLower();
	string communityUrl = (currentLanguageCode == "de" ? 
		"http://community.smartstore.com" :
        "http://community.smartstore.com/index.php?/&k=880ea6a14ea49e853634fbdc5015a024&setlanguage=1&cal_id=&langid=1");
    string docsUrl = "http://docs.smartstore.com/display/SMNET25/SmartStore.NET+Documentation+Home";
	var checkUpdateResult = ViewBag.CheckUpdateResult as CheckUpdateResult;
}

<div id="navbar" class="navbar navbar-inverse">
<div class="navbar-inner">
    
    <a class="brand" href="@Url.Action("Index", "Home", new { area = "Admin" })">
        <img src="~/Administration/Content/images/smnet.png" alt="smartstore.NET" />
    </a>

    @Html.Widget("admin_menu_before")
    @Html.Action("Menu", "Common", new { area = "Admin" })
    @Html.Widget("admin_menu_before")

    <div id="navbar-tools" class="pull-right">

		@if (currentCustomer != null && currentCustomer.IsRegistered())
		{
			<div class="btn-group pull-right">
				<a id="current-user" class="btn navbar-tool dropdown-toggle" data-toggle="dropdown" title="@userName" href='@Url.Action("Edit", "Customer", new { id = currentCustomer.Id, area = "Admin" })'>
					<em class="fa-stack fa-lg">
						<i class="fa fa-circle fa-stack-2x" style="x-color: #afbfff"></i>
						<i class="fa fa-user fa-stack-1x fa-inverse" style="color: #3b50ce"></i>
					</em>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a href="@Url.Action("Edit", "Customer", new { id = currentCustomer.Id, area = "Admin" })">
							<i class="fa fa-fw fa-user"></i>
							Account
						</a>
					</li>
					<li>
						<a href="@Url.Action("Logout", "Customer", new { area = "" })" class="disabled">
							<i class="fa fa-fw fa-sign-out"></i>
							@T("Admin.Header.Logout")
						</a>
					</li>
				</ul>
			</div>
		}	

		<div id="navtool-help" class="btn-group toppad pull-right">
			<button class="btn dropdown-toggle navbar-tool" title='@T("Admin.Help")' data-toggle="dropdown">
				<i class="fa fa-fw fa-question-circle"></i>
				@if (checkUpdateResult != null && checkUpdateResult.UpdateAvailable)
				{
					<span class="reddot" style="top: 5px; right: 7px"></span>
				}
			</button>
			<ul class="dropdown-menu">
				@if (checkUpdateResult != null && checkUpdateResult.UpdateAvailable)
				{
					<li>
						<a href='@Url.Action("CheckUpdate", new { area = "Admin" })'>
							<i class="fa fa-fw fa-level-up"></i>
							<strong>@T("Admin.CheckUpdate.UpdateAvailable")</strong>
							<span class="reddot" style="margin-left: 6px"></span>
						</a>
					</li>
				}
				<li>
					<a href="@docsUrl" data-lang="@currentLanguageCode" target="help">
						<i class="fa fa-fw fa-book"></i>
						@T("Admin.Help.Documentation")
					</a>
				</li>
				<li>
					<a href="@communityUrl" data-lang="@currentLanguageCode" target="help">
						<i class="fa fa-fw fa-comment"></i>
						@T("Admin.Help.Forums")
					</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="@Url.Action("About", "Home", new { area = "Admin" })">
						<i class="fa fa-fw fa-info-circle"></i>
						@T("Admin.Common.About")
					</a>
				</li>
			</ul>
		</div> 

		@Html.Action("LanguageSelector", "Common", new { area = "Admin" })

		<div class="btn-group toppad pull-right">
			<button class="btn dropdown-toggle navbar-tool" title='@T("Admin.Common.Actions")' data-toggle="dropdown">
				<i class="fa fa-fw fa-gear"></i>
			</button>
			<ul class="dropdown-menu">
				@foreach (var store in stores)
				{
					<li>
						<a href="@store.Url" title="@T("Admin.Header.PublicStore") - @store.Name">
							<i class="fa fa-fw fa-globe"></i>
							@store.Name.Truncate(32, "...")
						</a>
					</li>
				}
				<li>
					<a href='@Url.Action("Preview", "Theme")'>
						<i class="fa fa-fw fa-eye"></i>
						@T("Admin.Configuration.Themes.PreviewMode")
					</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="@Url.Action("ClearCache", "Common", new { previousUrl = Request.RawUrl, area = "Admin" })">
						<i class="fa fa-fw fa-trash-o"></i>
						@T("Admin.Header.ClearCache")
					</a>
				</li>
				<li>
					<a id="restart-application" href="#" data-url="@Url.Action("RestartApplication", "Common", new { previousUrl = Request.RawUrl, area = "Admin" })">
						<i class="fa fa-fw fa-power-off"></i>
						@T("Admin.Header.RestartApplication")
					</a>
				</li>
			</ul>
		</div>

    </div>

</div>
</div>


<script type="text/javascript">

    $(function () {

        $("#restart-application").click(function (e) {
            e.preventDefault();
            $.throbber.show({
                message: '@T("Admin.Header.RestartApplication.Progress")',
                callback: function () {
                    setLocation($(e.target).data("url"));
                    
                }
            });
            return false;
        });

        // add mainmenu tooltips;
        $('#tools [rel=tooltip]').tooltip({ 
            placement: 'bottom'
        });

    });
          
</script>

Presentation/SmartStore.Web/Administration/Views/Shared/_AdminLayout.cshtml
@using Telerik.Web.Mvc;
@using SmartStore.Services.Customers;
@using SmartStore.Web.Framework.UI;
@using SmartStore.Core;
@using SmartStore.Services.Localization;
@using SmartStore.Core.Domain.Localization;
@using SmartStore;

@* Please keep in mind that this layout view is also referenced and used by plugins! *@

@{
	Layout = "~/Administration/Views/Shared/_AdminRoot.cshtml";	
} 

<div id="page">
	@if (ViewData["warning.panel.message"] != null)
	{
		<div class="warning-panel-message fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @Html.Raw(ViewData["warning.panel.message"])
		</div>
	}
	
	@if (IsSectionDefined("header"))
	{
		@RenderSection("header")
	}
	else
	{
		<header>
			@if (IsSectionDefined("navbar"))
			{
				@RenderSection("navbar")
			}
			else
			{
				@Html.Widget("admin_navbar_before")
				@Html.Action("Navbar", "Common", new { area = "Admin" })
				@Html.Widget("admin_navbar_after")
			}

			<div id="breadcrumb">
				<!-- SiteMapPath here-->
				@Html.Widget("admin_breadcrumb").ToString().Trim()
			</div>
		</header>		
	}

    @Html.Widget("admin_content_before")
    <div id="content">
        @Html.Partial("_Notifications")
        <div class="cph">
            @RenderBody()
        </div>
		<div id="ajax-busy">
			<div class="bar"></div>
			<div class="bar"></div>
			<div class="bar"></div>
		</div>
    </div>
    @Html.Widget("admin_content_after")

</div>

Presentation/SmartStore.Web/Administration/Views/Shared/_AdminPopupLayout.cshtml
@{
	Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    Html.AddBodyCssClass("popup");
}
@section navbar
{
}
@RenderBody()

Presentation/SmartStore.Web/Administration/Views/Shared/_AdminRoot.cshtml
@using SmartStore;
@using SmartStore.Core;
@using SmartStore.Web.Framework.UI;

@{
    var currentUICulture = System.Threading.Thread.CurrentThread.CurrentUICulture;
    
    // page title
    string adminPageTitle = "";
    if (!string.IsNullOrWhiteSpace(ViewBag.Title))
    {
        adminPageTitle = ViewBag.Title + " / ";
    }
    adminPageTitle += T("Admin.PageTitle").Text;

	// add css assets
	var telerikCssRootPath = "~/Content/2012.2.607/";
	Html.AppendCssFileParts(
		"~/Content/font-awesome.css",
		telerikCssRootPath + "telerik.common.css",
		"~/Content/jquery.pnotify.default.css",
		"~/Content/jquery.pnotify.default.icons.css",
		"~/Administration/Content/theme.less");

    // add js assets (Head)
    Html.AppendScriptParts(ResourceLocation.Head,
        "~/Scripts/modernizr-2.7.2.js",
		// Telerik doesn't like jQuery 1.9+, a shame!
        "~/Administration/Scripts/jquery-1.8.3.js",
        "~/Scripts/globalize/globalize.js",
		"~/Scripts/smartstore.globalize.adapter.js");
        
    Html.AddScriptParts(ResourceLocation.Head, true,
        "~/Scripts/globalize/cultures/globalize.culture.{0}.js".FormatInvariant(currentUICulture.ToString()));

    // add js assets (Foot)
    var bootstrapJsRoot = "~/Content/bootstrap/js/";
    Html.AppendScriptParts(ResourceLocation.Foot,
        // jQuery UI Core
        "~/Scripts/jquery-ui/effect.js",
        "~/Scripts/jquery-ui/effect-transfer.js",
        "~/Scripts/jquery-ui/effect-shake.js",
        "~/Scripts/jquery-ui/position.js",
        // jQuery Validation
        "~/Scripts/jquery.unobtrusive-ajax.js",
        "~/Scripts/jquery.validate.js",
        "~/Scripts/jquery.validate.unobtrusive.js",
        // SmartStore system
        "~/Scripts/smartstore.system.js",
        "~/Scripts/underscore.js",
        "~/Scripts/underscore.string.js",
        "~/Scripts/underscore.mixins.js",
        "~/Scripts/smartstore.jquery.utils.js",
        "~/Scripts/jquery.ba-outside-events.js",
        "~/Scripts/jquery.preload.js",
        "~/Scripts/jquery.transit.js",
        "~/Scripts/jquery.menu-aim.js",
        "~/Scripts/smartstore.doAjax.js",
        "~/Scripts/jquery.addeasing.js",
        "~/Scripts/smartstore.eventbroker.js",
        "~/Scripts/smartstore.hacks.js",
		"~/Scripts/smartstore.common.js",
        // Bootstrap
        bootstrapJsRoot + "bootstrap-transition.js",
        bootstrapJsRoot + "bootstrap-alert.js",
        bootstrapJsRoot + "bootstrap-button.js",
        bootstrapJsRoot + "bootstrap-collapse.js",
        bootstrapJsRoot + "bootstrap-dropdown.js",
        bootstrapJsRoot + "bootstrap-modal.js",
        bootstrapJsRoot + "bootstrap-tooltip.js",
        bootstrapJsRoot + "bootstrap-popover.js",
        bootstrapJsRoot + "bootstrap-tab.js",
		bootstrapJsRoot + "bootstrap-typeahead.js",
        // Bootstrap custom
        bootstrapJsRoot + "custom/bootstrap-datetimepicker.js",
        // Shared UI
        "~/Scripts/smartstore.placeholder.js",
        "~/Scripts/select2.js",
        "~/Scripts/smartstore.selectwrapper.js",
        "~/Scripts/smartstore.throbber.js",
        "~/Scripts/smartstore.navbar.js",
        "~/Scripts/smartstore.thumbzoomer.js",
        "~/Scripts/smartstore.column-equalizer.js",
        "~/Scripts/smartstore.shrinkmenu.js",
        "~/Scripts/smartstore.scrollbutton.js",
        "~/Scripts/smartstore.tabselector.js",
        "~/Scripts/jquery.pnotify.js",
        "~/Scripts/jquery.scrollTo.js",
        "~/Scripts/jquery.serialScroll.js",
		"~/Scripts/jquery.sortable.js",
        // Admin
        "~/Administration/Scripts/admin.common.js",
        "~/Administration/Scripts/admin.globalinit.js");
}
<!DOCTYPE html>
<html class="no-js not-ready loading">
<head>
    <title>@adminPageTitle</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge; chrome=1" />

    <script>
        window.Res = {
            "Common.Notification": "@T("Common.Notification").ToString().EncodeJsString()",
        }
    </script>
    
    @Html.Partial("ConditionalComments")
    @Html.MetaAcceptLanguage()

    @Html.SmartCssFiles(this.Url, ResourceLocation.Head)
    @Html.SmartScripts(this.Url, ResourceLocation.Head)

    <link rel="shortcut icon" href="~/Administration/favicon.ico" />

</head>
<body class="@Html.BodyCssClass()"@(Html.BodyId())>   
	@RenderBody()
	@RenderSection("foot", required: false)
    @Html.SmartCssFiles(this.Url, ResourceLocation.Foot)
    @Html.SmartScripts(this.Url, ResourceLocation.Foot)

	<!--These need to be at the end of the page to ensure that all the controls requiring scripts have been rendered-->
	@(Html.Telerik().ScriptRegistrar()
		.jQuery(false)
		.jQueryValidation(false)
		.Globalization(true)
	)
</body>
</html>